FORMAT: 1A
HOST: https://v1.report.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.Report
JAVADEFAULTNAMESPACE: io.dudesolutions.report
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK
NULLIFY404: TRUE
VALIDATEREQUIREDPARAMETERS: FALSE
COLLECTPARAMETERS: TRUE
ARRAYSERIALIZATION: Plain

# Dude Report Api

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
*Report Api* uses OAuth v2 Authentication. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

New to *OAuth*?  Check out the [OAuth Bible](http://oauthbible.com/) for good reference material.

Report API also allows a bearer token to be passed in the query string. (i.e. /somepath?accessToken=*token*)

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.

Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
Common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.

In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:

        {
            "message": "SOME MESSAGE",
            "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
            "stackTrace": "Null, Typically"
        }

## Data Restriction
Depending on the access level granted to the calling client certain data elements throughout this API will be removed and not returned.

## Dates & Times
All dates and times are represented in [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) format.  In addition, *<ApiName>* will always provide [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).

The API is capable of parsing most date and time formats, however we do require UTC dates and times be provided from all calling systems.  We highly recommend you utilize the ISO-8601 standard when communicating dates and time to the API as well.

## Known Issues
None at this time

## Documentation Notes
In Progress

# Group System Information
Check API System Information.

## S.I. Check [/]
Retrieve api version, vitals, links, etc.

### GET

+ Response 200 (application/json)
    + Attributes (System Information)

# Group Heartbeat
Check health of dependent services.

## Heartbeat Check [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json)
    + Headers

            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID

    + Attributes (Heartbeat)


# Group Export
Check export endpoints.

## Work Orders [/accounts/{accountId}/export/workorders{?orderby,q,actiontaken,assignees,completiondatefrom,completiondateto,createdby,displayid,priority,purpose,requestdatefrom,requestdateto,requestedby,status,worktype,businessasset,project}]
This collection allows for workorder data to be returned as an Excel document.

+ Parameters
    + accountId: 1 (required, number) - {INT} ID of the account in the form of an integer
    + orderby: Quantity asc (string, optional) - A string describing the ordering to perform on the collection.
    + q (string, optional) - A free form filter mechanism.
    + actiontaken: Fixed the chair (string, optional) - Filter by action taken text.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + createdby: 1 (number, optional) - {INT} Filter by the user who created the work order.
    + displayid: 123 (string, optional) - Filter by the display ID of the work order.
    + priority: Low (enum[string], optional) - Filter by the priority of work orders.
        + Members
            + Low (string)
            + Medium (string)
            + High (string)
            + Emergency (string)
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + requestedby: 1 (number, optional) - {ARRAY} {INT} Filter by the work order requester.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type assigned to the work order.
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + project: 1 (number, optional) - {ARRAY} {INT} Filter by the project assigned to the work order.

### GET

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    This returns an excel document as results. {HTTPRESPONSE}

    + Headers

            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=WorkOrderExport_2016-01-22.xlsx
            Content-Length:8306

## Work Orders By Purpose [/accounts/{accountId}/export/workordersbypurpose{?orderby,completiondatefrom,completiondateto,assignees,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,Members,businessasset,assetrollup,timezone}]
This collection allows for workorder data to be organized by purposes with relevant counts and returned as an Excel document.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    This returns an excel document as results. {HTTPRESPONSE}

    + Headers

            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=WorkOrdersByPurpose_2016-01-22.xlsx
            Content-Length:8306

## Work Orders By Work Type [/accounts/{accountId}/export/workordersbyworktype{?orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
This collection allows for workorder data to be organized by work type with relevant counts and returned as an Excel document.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    This returns an excel document as results. {HTTPRESPONSE}

    + Headers

            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=WorkOrdersByWorkType_2016-01-22.xlsx
            Content-Length:8306

## Failures By Asset [/accounts/{accountId}/export/failuresbyasset{?orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assingees}]
This collection allows for failure data to be organized by asset with relevant counts and returned as an Excel document.

     + Parameters
         + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
         + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
         + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
         + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
         + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
         + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
         + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
         + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
         + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
         + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
         + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
         + status: NewRequest (enum[string], optional) - Filter by the work order status.
             + Members
                 + NewRequest (string)
                 + WorkInProgress (string)
                 + Completed (string)
                 + Void (string)
                 + OnHold (string)
         + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
         + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
         + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
         + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    This returns an excel document as results. {HTTPRESPONSE}

    + Headers

            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=FailuresByAsset_2016-01-22.xlsx
            Content-Length:8306

## Work Orders By Asset [/accounts/{accountId}/export/workordersbyasset{?orderby,completiondatefrom,completiondateto,priority,purpose,requestdatefrom,requestdateto,duedatefrom,duedateto,status,worktype,businessasset,assetrollup,timezone}]
This collection allows for workorder data to be organized by asset with relevant counts and returned as an Excel document.

   + Parameters
       + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
       + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
       + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
       + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
       + priority: Low (enum[string], optional) - Filter by the priority of work orders.
           + Members
               + Low (string)
               + Medium (string)
               + High (string)
               + Emergency (string)
       + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
       + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
       + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
       + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
       + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
       + status: NewRequest (enum[string], optional) - Filter by the work order status.
           + Members
               + NewRequest (string)
               + WorkInProgress (string)
               + Completed (string)
               + Void (string)
               + OnHold (string)
       + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
       + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
       + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
       + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    This returns an excel document as results. {HTTPRESPONSE}

    + Headers

            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=FailuresByAsset_2016-01-22.xlsx
            Content-Length:8306

# Group Dashboard
Dashboard endpoints

## On Time Ratio [/accounts/{accountId}/dashboard/ontimeratio{?startDate,endDate}]
This endpoint returns counts of work orders on time and over due for the given time frame base on scheduled date.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + startDate: `2015-01-01T00:00:00.123Z` (string, required) - {DATETIME} The start date and time in ISO-8601
    + endDate: `2015-01-07T00:00:00.123Z` (string, required) - {DATETIME} The end date and time in ISO-8601

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (On Time Ratio)

# Group Reports
Check report endpoints.

## Employee Summary Collection [/accounts/{accountId}/reports/employees/summary{?page,pagesize,orderby,datefrom,dateto,purpose,worktype,businessasset,assignees,assetrollup,timezone}]
This collection allows for workorder data to be organized by asset and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + datefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by date, starting from.
    + dateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Employee Summary], required)

## Asset Failure Reason Collection [/accounts/{accountId}/reports/assets/{assetId}/failures{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
This collection allows for workorder data to be organized by asset failure reasons and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + assetId: 1 (required, number) - {INT} ID of the asset in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Asset Failure Reason], required)

## Asset Work Type Collection [/accounts/{accountId}/reports/assets/{assetId}/worktypes{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
This collection allows for workorder data to be organized by asset and work type then return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + assetId: 1 (required, number) - {INT} ID of the asset in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Asset Failure Reason], required)

## Asset Summary Collection [/accounts/{accountId}/reports/assets/summary{?page,pagesize,orderby,completiondatefrom,completiondateto,priority,purpose,requestdatefrom,requestdateto,duedatefrom,duedateto,status,worktype,businessasset,assignees,assetrollup,timezone}]
This collection allows for workorder data to be organized by asset and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + priority: Low (enum[string], optional) - Filter by the priority of work orders.
        + Members
            + Low (string)
            + Medium (string)
            + High (string)
            + Emergency (string)
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Asset Summary], required)

## Asset Grand Totals [/accounts/{accountId}/reports/assets/totals{?completiondatefrom,completiondateto,priority,purpose,requestdatefrom,requestdateto,duedatefrom,duedateto,status,worktype,businessasset,assignees,assetrollup,timezone}]
Returns the summarized costs and counts of assets.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + priority: Low (enum[string], optional) - Filter by the priority of work orders.
        + Members
            + Low (string)
            + Medium (string)
            + High (string)
            + Emergency (string)
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Asset Grand Totals)

## Assignee Summary Collection [/accounts/{accountId}/reports/assignees/summary{?page,pagesize,orderby,assigneeid}]
This collection allows for workorder data to be organized by assignee and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + assigneeid: 1 (number, optional) - {INT} Filter by the assignee id.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Assignee Summary], required)

## Failure Summary Collection [/accounts/{accountId}/reports/failures/summary{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
This collection allows for workorder data to be organized by overall failures and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Failure Summary], required)

## Purpose Summary Collection [/accounts/{accountId}/reports/purposes/summary{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees,returnAverages}]
This collection allows for workorder data to be organized by purposes and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + returnAverages: false (boolean, optional) - Flag to indicate whether to return the sum or average of the data. Defaults to false.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Purpose Summary], required)

## Purpose Grand Totals[/accounts/{accountId}/reports/purposes/totals{?completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
Returns the summarized costs and counts of work orders with an associated purpose.

+ Parameters
   + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
   + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
   + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
   + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
   + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
   + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
   + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
   + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
   + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
   + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
   + status: NewRequest (enum[string], optional) - Filter by the work order status.
       + Members
           + NewRequest (string)
           + WorkInProgress (string)
           + Completed (string)
           + Void (string)
           + OnHold (string)
   + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
   + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
   + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
   + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Report Data)

## Work Type Summary Collection [/accounts/{accountId}/reports/worktype/summary{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees,returnAverages}]
This collection allows for workorder data to be organized by work type and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.
    + returnAverages: false (boolean, optional) - Flag to indicate whether to return the sum or average of the data. Defaults to false.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Work Type Summary], required)

## Work Type Grand Totals [/accounts/{accountId}/reports/worktype/totals{?completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees]
Returns the summarized costs and counts of work orders with an associated work type.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Report Data)

## Status Summary Collection [/accounts/{accountId}/reports/statuses/summary{?page,pagesize,orderby,completiondatefrom,completiondateto,purpose,worktype,failurereason,requestdatefrom,requestdateto,duedatefrom,duedateto,status,businessasset,assetrollup,timezone,assignees}]
This collection allows for workorder data to be organized by purposes and return relevant counts.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer
    + page: 1 (number, optional) - {INT} The page to request from the collection.
    + pagesize: 1000 (number, optional) - {INT} The number of records to load in a page from the collection.
    + orderby: Id desc (string, optional) - A string describing the ordering to perform on the collection.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by completion date, until.
    + purpose: 1 (number, optional) - {ARRAY} {INT} Filter by the purpose of work orders.
    + worktype: 1 (number, optional) - {ARRAY} {INT} Filter by the work type.
    + failurereason: 1 (number, optional) - {ARRAY} {INT} Filter by the failure reason of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by the request date, until.
    + duedatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, starting from.
    + duedateto: `2015-01-01T00:00:00.000Z` (string, optional) - {DATETIME} Filter by due date, until.
    + status: NewRequest (enum[string], optional) - Filter by the work order status.
        + Members
            + NewRequest (string)
            + WorkInProgress (string)
            + Completed (string)
            + Void (string)
            + OnHold (string)
    + businessasset: 1 (number, optional) - {ARRAY} {INT} Filter by the business asset assigned to the work order.
    + assetrollup: false (boolean, optional) - Flag to indicate whether or not to include child asset data in the aggregates.
    + timezone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + assignees: 1 (number, optional) - {ARRAY} {INT} Filter by assignees.

### GET

+ Response 200 (application/json; charset=utf-8)
    + Attributes (Base Collection Response)
        + `data` (array[Status Summary], required)


# Group PDF
PDF export endpoints.

## Work Order PDF Export [/accounts/{accountId}/pdf/workorders/{?workOrderId,timeZone}]
This endpoint returns a work order in a printable PDF format.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer.
    + workOrderId: 12345 (required, number) - {INT} ID of the work order in the form of an integer.
    + timeZone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.

### GET

+ Response 200 (application/pdf)
    This returns an PDF document as results. {HTTPRESPONSE}

## Work Orders PDF Export [/accounts/{accountId}/pdf/workorders/{?isTemporary,timeZone,workOrderId}]
This endpoint returns a URI to the generated PDF.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer.
    + timeZone: Etc/UTC (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
    + workOrderId: 12345 (array[number], required) - {INT} Filter by the work order IDs.
    + isTemporary: false (boolean, optional) - Flag to indicate whether or not the file should be deleted during the next cleanup process. The default is false.

### POST

+ Response 201 (application/json)
    + Attributes(File Upload Info)

## Work Orders Summary Export [/accounts/{accountId}/pdf/workorders]
This endpoint returns a URI to the generated work order summary PDF.

+ Parameters
    + accountId: 2 (required, number) - {INT} ID of the account in the form of an integer.

### POST

+ Request
    + Attributes (Work Order PDF Filter)

+ Response 201 (application/json)
    + Attributes(File Upload Info)

# Data Structures

## System Information (object)
Represents the System Information response.

### Properties
+ `application`: `Dude Report Api` (string, required) - The name of the application.
+ `version` : `1.0.0.0` (string, required) - The assembly version.
+ `apiVersion` : `1.0.0.0` (string, required) - The API version.
+ `vitals` (Heartbeat, required) - The state of the system dependencies.
+ `links` (array[System Links], required) - The API routes.

## System Links (object)
Represents the API routes.

### Properties
+ `endpoint` : `AssigneeSummary` (string, required) - The name of the endpoint.
+ `action` : `Get` (string, required) - The REST action.
+ `route` : `/accounts/{accountId}/reports/assignees/summary{?page,pagesize,orderby}` (string, required) - The route to the endpoint.

## Heartbeat (object)
Represents a heartbeat response.

### Properties
+ `cachevitalcheck`: true (boolean, required) - true is cache is online.
+ `reportdbvitalcheck`: true (boolean, required) - true if ReportDB is online

## Base Collection Response (object)
Represents a paged object.

### Properties
+ `page`: 1 (number, required) - {INT} The current page provided in the response data.
+ `pageSize`: 1000 (number, required) - {INT} The page size returned in the response data.
+ `dataSize`: 1000 (number, required) - {INT} The total records returned in the response.
+ `total`: 2000 (number, required) - {INT} The total number of records available in the collection.

## Asset Failure Reason (object)
Represents an asset failure reason object.

### Properties
+ `failureReason` (Failure Reason, required) - The failure reason for the asset failure reason.
+ `count`: 5 (number, required) - {INT} The number of failure reasons.

## Asset Work Type (object)
Represents an asset work type object.

### Properties
+ `workType` (Work Type, required) - The work type for the workorder associated to the asset.
+ `count`: 5 (number, required) - {INT} The number of work orders with this work type.

## Employee Summary (object)
Represents an employee summary object.

### Properties
+ `assignee` (User, required) - The assignee user for the employee summary.
+ `openWorkOrders` (number, required) - The number of open work orders the user has.
+ `completedWorkOrders` (number, required) - The number of work orders the user completed.
+ `laborHours` (number, required) - The number of labor hours the user spent.

## Asset Summary (object)
Represents an asset summary object.

### Properties
+ `asset` (Asset, required) - The asset for the asset summary.
+ `cost` (Cost, required) - The cost for the asset summary.
+ `count` (Count, required) - The counts for the asset summary.
+ `assetDescendants` (Report Data, required) - The report data for the asset summary.
+ `totalsWithDescendants` (Report Data, required) - The report data for the asset summary.

## Assignee Summary (object)
Represents an assignee summary object.

### Properties
+ `assignee` (User, required) - The assignee user for the assignee summary.
+ `count` (Count, required) - The counts for the assignee summary.

## Failure Summary (object)
Represents a failure summary object.

### Properties
+ `asset` (Asset, required) - The asset linked with this failure summary.
+ `self` (Failure Detail, required) - The asset's failure details.
+ `descendants` (Failure Detail, required) - The asset's descendants failure details.
+ `totals` (Failure Detail, required) - The asset's total failure details, including its descendants.

## Purpose Summary (object)
Represents a purpose summary object.

### Properties
+ `purpose` (Purpose, required) - The purpose for the purpose summary.
+ `cost` (Cost, required) - The cost for the purpose summary.
+ `count` (Count, required) - The counts for the purpose summary.

## Work Type Summary (object)
Represents a work type object.

### Properties
+ `workType` (Work Type, required) - The work type for the work type summary.
+ `cost` (Cost, required) - The cost for the work type summary.
+ `count` (Count, required) - The counts for the work type summary.

## Status Summary (object)
Represents a status summary object.

### Properties
+ `status`: NewRequest (string, required) - The status for the status summary. Acceptable values: NewRequest, WorkInProgress, Complete, Void, OnHold.
+ `count`: 5 (number, required) - {INT} The counts for the status summary.

## Asset (object)
Represents an asset with base properties.

### Properties
+ `id`: 94020 (number, required) - {INT} The unique ID for the asset.
+ `value`: vbykbh (string, required) - The name of the asset.
+ `isActive`: true (boolean, required) - IsActive check to ensure the asset is active.
+ `description`: A New Asset (string, optional) - The name of the asset.
+ `AncestorIdPath`: /39 (string, required) - The anscestor id path.
+ `AncestorNamePath`: |igeujs (string, required) - The anscestor name path.

## Cost (object)
Represents a cost object.

### Properties
+ `labor`: 300.01 (number, required) - The sum of labor costs.
+ `purchase`: 200.01 (number, required) - The sum of purchase costs.
+ `service`: 200.01 (number, required) - The sum of service costs.
+ `total`: 500.02 (number, required) - The total sum of all costs.

## Count (object)
Represents a count object.

### Properties
+ `workOrders`: 9 (number, required) - {INT} The number of workorders.
+ `laborHours`: 30 (number, required) - The number of labor hours.

## Report Data (object)
Represents a report data object.

### Properties
+ `cost` (Cost, required) - The costs of the report data.
+ `count` (Count, required) - The counts of the report data.

## Failure Detail (object)
Represents a failure detail object.

### Properties
+ `failures`: 5 (number, required) - {INT} The number of failures.

## Failure Reason (object)
Represents a failure reason with base properties.

### Properties
+ `id`: 1 (number, required) - {INT} The unique ID for the failure reason.
+ `name`: Accidental Damage (string, required) - The name of the failure reason.
+ `isActive`: true (boolean, required) - IsActive check to ensure the failure reason is active.

## Purpose (object)
Represents a purpose with base properties.

### Properties
+ `id`: 2 (number, required) - {INT} The unique ID for the purpose.
+ `value`: Evaluation (string, required) - The name of the purpose.
+ `isActive`: true (boolean, required) - IsActive check to ensure the purpose is active.

## Work Type (object)
Represents a work type with base properties.

### Properties
+ `id`: 2 (number, required) - {INT} The unique ID for the work type.
+ `name`: Evaluation (string, required) - The name of the work type.
+ `isActive`: true (boolean, required) - IsActive check to ensure the work type is active.

## User (object)
Represents a user with base properties.

### Properties
+ `id`: 1 (number, required) - {INT} The ID of the user.
+ `firstName`: John (string, required) - The first name of the user.
+ `lastName`: Smith (string, required) - The last name of the user.
+ `email`: john.smith@dudesolutions.io (string, required) - The email address of the user.
+ `isEnabled`: true (boolean, required) - A flag indicating whether the user is enabled or disabled.

## On Time Ratio (object)
Represents work orders on time or overdue.

### Properties
+ `onTime`: 1 (number, required) - {INT} Count of on time work orders.
+ `overDue`: 1 (number, required) - {INT} Count of over due work orders.

## File Upload Info (object)
Represents a file resource with base properties.

### Properties
+ `id`: 1 (number, required) - {INT} The ID of the file.
+ `shareableUri`: https://file.dudesoln.com/file/public/rftuyinm3d546ft7uybinod4f578ybiunok68gyiunokm67g8yiunokm (string, required) - The URI that can be used to access the file without logging in.

## Work Order PDF Filter (object)
Represents the filter for work order PDFs

### Properties
+ `timeZone`: `Etc/UTC` (string, optional) - A string denoting the time zone. The default is “Etc/UTC”.
+ `workOrderIds`: (array[number], required) - {INT} The IDs of the work orders to filter on.

## Asset Grand Totals (object)
Represents the summarized costs and counts of assets.

### Properties
+ `asset` (Report Data, required) - The cost and count asset data.
+ `assetDescendants` (Report Data, required) - The cost and count asset descendant data.
+ `totalsWithDescendants` (Report Data, required) - The cost and count asset data with the descendant data.