FORMAT: 1A
HOST: https://v1.report.dudesolutions.io

USECOMMONSDKLIBRARY: TRUE
GENERATEASYNCCODE: TRUE
GENERATEINTERFACES: TRUE
USEMETHODPREFIX: TRUE
USEMODELPOSTFIX: FALSE
USECONTROLLERPOSTFIX: FALSE
USEENUMPOSTFIX: FALSE
USECONSTRUCTORSFORCONFIG: TRUE
CSHARPDEFAULTNAMESPACE: DSI.SDK.Report
JAVADEFAULTNAMESPACE: io.dudesolutions.report
BRANDLABEL: Dude Solutions, Inc.
USERAGENT: Dude SDK

# Dude Report Api
![Dude Solutions](https://dudesolutions.com/assets/img/logo.png)

## Reference
Good reference document: https://raw.githubusercontent.com/apiaryio/api-blueprint/master/examples/Polls%20API.md

## Authentication
*Report Api* uses OAuth v2 Authentication. First you create a new (or acquire existing) OAuth v2 token using [DudeAuth](https://www.dudeauth.com/).

New to *OAuth*?  Check out the [OAuth Bible](http://oauthbible.com/) for good reference material.

Report API also allows a bearer token to be passed in the query string. (i.e. /somepath?accessToken=*token*) 

## Media Types
Where applicable this API uses the *JSON* media-type to represent resources.

Requests and responses with a message-body use plain JSON to set or update resources.

## Error States
Common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used throughout this API.

In addition to standard response codes the response object returned from the server during an exception event may contain additional information in the following JSON format:

        {
            "message": "SOME MESSAGE",
            "dudeReferenceId": "3523845A-4729-4CCB-9E16-01DEADF6C2DF",
            "stackTrace": "Null, Typically"
        }
        
## Data Restriction
Depending on the access level granted to the calling client certain data elements throughout this API will be removed and not returned.

## Dates & Times
All dates and times are represented in [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) format.  In addition, *<ApiName>* will always provide [Coordinated Universal Time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time).

The API is capable of parsing most date and time formats, however we do require UTC dates and times be provided from all calling systems.  We highly recommend you utilize the ISO-8601 standard when communicating dates and time to the API as well.

## Known Issues
None at this time

## Documentation Notes
In Progress

# Group Heartbeat
Check health of dependant services

## Heartbeat [/heartbeat]
The heartbeat is exposed and provided to check for availability of the service.
Any response that does not provide a ```200 OK``` response code should be treated as an error.

### GET

+ Response 200 (application/json)
    + Headers
    
            X-Dude-Api-Limit: Unlimited or Number
            X-Dude-Api-Remaining: Unlimited or Number
            X-Dude-Api-Server: Api Server ID
            
    + Attributes (Heartbeat)

# Group Export

## Work Orders [/accounts/{accountId}/export/workorders{?orderby,q,actiontaken,assignees,completiondatefrom,completiondateto,createdby,displayid,priority,purpose,requestdatefrom,requestdateto,requestedby,status,workcategory,businessasset}]
Work order export endpoint

+ Parameters
    + accountId: 1 (required, number) - #INT ID of the account in the form of an integer
    + orderby: Quantity asc (string, optional) - A string describing the ordering to perform on the collection.
    + q (string, optional) - A free form filter mechanism.
    + actiontaken: Fixed the chair (string, optional) - Filter by action taken text.
    + assignees: 1 (array[number], optional) - Filter by assignees.
    + completiondatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - Filter by completion date, starting from.
    + completiondateto: `2016-01-01T00:00:00.000Z` (string, optional) - Filter by completion date, until.
    + createdby: 1 (number, optional) - #INT Filter by the user who created the work order.
    + displayid: 123 (string, optional) - #INT Filter by the display ID of the work order.
    + priority: Low (array[Priority], optional) - Filter by the priority of work orders.
    + purpose: 1 (array[number], optional) - Filter by the purpose of work orders.
    + requestdatefrom: `2015-01-01T00:00:00.000Z` (string, optional) - Filter by request date, starting from.
    + requestdateto: `2016-01-01T00:00:00.000Z` (string, optional) - Filter by the request date, until.
    + requestedby: 1 (array[number], optional) - Filter by the work order requester.
    + status: NewRequest (array[Work Order Status], optional) - Filter by the work order status.
    + workcategory: 1 (array[number], optional) - Filter by the work category assigned to the work order.
    + businessasset: 1 (array[number], optional) - Filter by the business asset assigned to the work order.

### GET
This returns an excel document as results.

+ Response 200 (application/vnd.openxmlformats-officedocument.spreadsheetml.sheet)
    + Headers
    
            Cache-Control:no-cache
            Connection:keep-alive
            Content-Disposition:attachment; filename=WorkOrderExport_2016-01-22.xlsx
            Content-Length:8306


# Data Structures

## Heartbeat (object)
Represents a heartbeat response.

### Properties
+ `vitalCheck`: true (boolean, required) - Vital check to ensure something is online.

## Work Order Status (enum)
+ NewRequest (string)
+ WorkInProgress (string)
+ Completed (string)
+ Void (string)

## Priority (enum)
+ Low (string)
+ Medium (string)
+ High (string)
+ Emergency (string)
