# Data Structures

## Heartbeat (object)
Represents a heartbeat response.

### Properties
+ `cachevitalcheck`: true (boolean, required) - true is cache is online.
+ `reportdbvitalcheck`: true (boolean, required) - true if ReportDB is online
