## Asset Summary (object)
+ `asset` (Asset, required) - The asset for the asset summary.
+ `cost` (Cost, required) - The cost for the asset summary.
+ `count` (Count, required) - The counts for the asset summary.
