## Asset (object)
+ `id` (number, required) - #INT The unique ID for the asset.
+ `value` (string, required) - The name of the asset.
+ `isActive` (boolean, required) - IsActive check to ensure the asset is active.
+ `description` (string, optional) - The name of the asset.
+ `AncestorIdPath` (string, required) - The anscestor id path.
+ `AncestorNamePath` (string, required) - The anscestor name path.
