## Base Collection Response (object)
+ `page`: 1 (number, required) - #INT The current page provided in the response data.
+ `pageSize`: 1000 (number, required) - #INT The page size returned in the response data.
+ `dataSize` (number, required) - #INT The total records returned in the response.
+ `total` (number, required) - #INT The total number of records available in the collection.
