## Failure Reason (object)
+ `id` (number, required) - #INT The unique ID for the failure reason.
+ `name` (string, required) - The name of the failure reason.
+ `isActive` (boolean, required) - IsActive check to ensure the failure reason is active.
