## Failure Summary (object)
+ `asset` (Asset, required) - The asset for the failure summary.
+ `failureReason` (Failure Reason, required) - The failure reason for the failure summary.
+ `failureDetail` (Failure Detail, required) - The failure detail for the failure summary.
