## Purpose Summary (object)
+ `purpose` (Purpose, required) - The purpose for the purpose summary.
+ `cost` (Cost, required) - The cost for the purpose summary.
+ `count` (Count, required) - The counts for the purpose summary.
