## Purpose (object)
+ `id` (number, required) - #INT The unique ID for the purpose.
+ `value` (string, required) - The name of the purpose.
+ `isActive` (boolean, required) - IsActive check to ensure the purpose is active.
